#!/usr/bin/env python3
"""修正版：データ設計の正確な説明"""

def main():
    print("="*100)
    print("【データ設計の正確な説明】")
    print("="*100)
    print()
    
    print("## 重要な訂正")
    print()
    print("「他のエンティティ」= 完全に無関係な第三者")
    print("  ↓ 【誤り】")
    print("「他のエンティティ」= 選択されなかった近傍 + 完全に無関係な第三者")
    print()
    
    print("="*100)
    print("【正確な処理フロー】")
    print("="*100)
    print()
    
    print("ステップ1: 全近傍の収集 (N)")
    print("-"*100)
    print("  ターゲット (?a) に繋がるすべてのエンティティ")
    print("  例:")
    print("    - 友人関係: ?a friend ?f1, ?a friend ?f2, ?a friend ?f3")
    print("    - 受賞作品: ?award1 award_winner ?a, ?award2 award_winner ?a")
    print("    - 教育機関: ?school students_graduates ?a")
    print("  → N = {?f1, ?f2, ?f3, ?award1, ?award2, ?school, ...}")
    print()
    
    print("ステップ2: 近傍のサンプリング (R ⊆ N)")
    print("-"*100)
    print("  drop_ratio = 0.7 で 70% を選択")
    print("  例: N = {?f1, ?f2, ?f3, ?award1, ?award2, ?school}")
    print("      R = {?f1, ?award1, ?award2, ?school}  (70%選択)")
    print("      N \\ R = {?f2, ?f3}  (30%選択されず)")
    print()
    print("  重要: 友人 ?f2, ?f3 は「近傍だが選択されなかった」")
    print()
    
    print("ステップ3: D1 の構築 (選択された近傍の情報削除)")
    print("-"*100)
    print("  R に含まれるエンティティに関連するトリプルを削除")
    print("  削除されるトリプル:")
    print("    - ?a friend ?f1  (友人関係)")
    print("    - ?f1 nationality ?b1  (友人の国籍)")
    print("    - ?award1 award_winner ?a  (受賞)")
    print("    - ?award1 nationality ?b2  (※受賞作品に国籍があれば)")
    print("    - ?school students_graduates ?a  (教育)")
    print("    - ... など")
    print()
    print("  保持されるトリプル:")
    print("    - ?a friend ?f2  (選択されなかった友人)")
    print("    - ?a friend ?f3  (選択されなかった友人)")
    print()
    
    print("ステップ4: D2 の構築 (グローバルな知識の提供)")
    print("-"*100)
    print("  条件: h ∉ T, t ∉ T, h ∉ R, t ∉ R かつ r = target_relation")
    print()
    print("  D2 に含まれる可能性のあるエンティティ:")
    print("    1. 選択されなかった近傍 (N \\ R)")
    print("       - ?f2 nationality ?b2")
    print("       - ?f3 nationality ?b3")
    print("       ※友人だが選択されなかったため、その nationality が利用可能")
    print()
    print("    2. 完全に無関係な第三者")
    print("       - ?stranger1 nationality ?b4")
    print("       - ?stranger2 nationality ?b5")
    print("       ※ターゲットと一切繋がりのない人物")
    print()
    print("  other_target_ratio = 0.5 で 50% をサンプリング → D2")
    print()
    
    print("="*100)
    print("【ルール適用の具体例】")
    print("="*100)
    print()
    
    print("ルール: ?f nationality ?b ∧ ?a friend ?f => ?a nationality ?b")
    print()
    
    print("シナリオ1: 友人 ?f1 が選択された場合 (70%の確率)")
    print("-"*100)
    print("  ?a friend ?f1  → D1 で削除済み（利用不可）")
    print("  ?f1 nationality ?b1  → D1 で削除済み（利用不可）")
    print("  → このルールは ?f1 に対して適用できない")
    print()
    
    print("シナリオ2: 友人 ?f2 が選択されなかった場合 (30%の確率)")
    print("-"*100)
    print("  ?a friend ?f2  → train.txt に残っている（利用可能）")
    print("  ?f2 nationality ?b2  → D2 に含まれる可能性（other_target_ratio次第）")
    print("  → このルールは ?f2 に対して適用できる可能性")
    print()
    
    print("シナリオ3: 外部から新しい友人を発見した場合")
    print("-"*100)
    print("  外部情報源から: ?a friend ?f_new を取得")
    print("  ?f_new nationality ?b_new  → D2 に含まれる可能性")
    print("  → このルールを適用して ?a の nationality を推論")
    print()
    
    print("="*100)
    print("【設計の意図】")
    print("="*100)
    print()
    print("✓ 部分的な情報削除 (drop_ratio=0.7)")
    print("  → 完全に情報が失われたわけではない")
    print("  → 現実的なシナリオ: 一部の情報が欠けている状態")
    print()
    print("✓ グローバルな知識の提供 (other_target_ratio=0.5)")
    print("  → 選択されなかった近傍の属性も利用可能")
    print("  → 無関係な第三者の属性も利用可能")
    print("  → Hornルールによる推論を可能にする")
    print()
    print("✓ 現実的な評価")
    print("  → 「すべての情報がない」ではなく「限られた情報からの推論」")
    print("  → 知識補完の効果を測定できる")

if __name__ == "__main__":
    main()
